repos:
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: "v1.6.0"
    hooks:
      - id: autopep8
        args: ["--in-place", "--max-line-length", "100"]

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          [
            "flake8-quotes==3.2.0",
            "flake8-print==4.0.0",
            "flake8-logging-format==0.6.0",
            "flake8-sfs==0.0.3",
          ]
