run_params:
  name: adversarial_cifar10_effnetb0
  seed: 1

datamodule:
  name: ClassificationDataModule
  params:
    data_dir: "/home/judicator/data/cifar10/train"
    test_data_dir: "/home/judicator/data/cifar10/test"
    input_shape: [32, 32]
    val_split: 0.1
    batch_size: 256
    use_weighted_sampler: False
    pin_memory: True

task:
  name: ClassificationTask
  params:
    debug: False
    network:
      name: EfficientNetB0
      params:
        pretrained: True
    loss:
      name: CrossEntropyLoss
      params:
        is_weighted: False
    attack:
      name: CW
      params:

    metrics:
      - name: F1Score
    optimizer:
      name: Adam
      params:
        lr: 0.001

callbacks:
  - name: ModelCheckpoint
    params:
      monitor: val_f1score
      mode: max
      verbose: True
  - name: EarlyStopping
    params:
      monitor: val_f1score
      mode: max
      verbose: True
      patience: 10


trainer_params:
  max_epochs: 300
  gpus: 1

export_params:
  output_name: cifar10_effnetb0
  batch_size: 1
