run_params:
  name: concrete_cracks_classification
  seed: 1

datamodule:
  name: ClassificationDataModule
  params:
    data_dir: "/home/judicator/d/data/Dataset"
    test_data_dir: "/home/judicator/d/data/concrete_test"
    classes:
      - Negative
      - Positive
    input_shape: [227, 227]
    val_split: 0.1
    batch_size: 32
    use_weighted_sampler: False
    pin_memory: True
    num_workers: 2

task:
  name: ClassificationTask
  params:
    debug: False

    network:
      name: EfficientNetLite0
      params:
        pretrained: True

    loss:
      name: CrossEntropyLoss
      weighted: False
      params:
        {}

    optimizer:
      name: Adam
      params:
        lr: 0.001

    scheduler:
      {}

callbacks:
  EarlyStopping:
    monitor: val_loss
    mode: min
    patience: 5
    verbose: True
  ModelCheckpoint:
    verbose: True

trainer_params:
  max_epochs: 100
  gpus: 1

export_params:
  output_name: "ccc_model"
  batch_size: 32
