run_params:
  name: example_detection
  seed: 1

datamodule:
  name: DetectionDataModule
  params:
    images_dir: "/home/judicator/ev/dvc/sbc_core/Datasets/ObjectDetection_c1_c3_c6_person/ev_datasets_coco/images"
    annotation_files: "/home/judicator/ev/dvc/sbc_core/Datasets/ObjectDetection_c1_c3_c6_person/ev_datasets_coco/annotations/ev_2021_03.json"
    image_size: [320, 320]
    batch_size: 16
    val_split: 0.1
    test_split: 0.0

task:
  name: DetectionTask
  params:
    model:
      name: MobileDetCPU
      params:
        num_classes: 1
        anchor_params:
          image_size: [320, 320]
          min_level: 4
          max_level: 9
          num_scales: 1
          anchor_scale: 1.0
    optimizer:
      name: Adam
      params:
        lr: 0.001
    debug: True

callbacks:
  - name: ModelCheckpoint
    params:
      monitor: val_loss
      mode: min
      verbose: True

trainer_params:
  max_epochs: 100
  gpus: 1

export_params:
  output_name: example_detection
  to_onnx: False
