run_params:
  name: example_classification
  seed: 1

datamodule:
  name: ClassificationDataModule
  params:
    data_dir: "/path/to/train/dataset/folder"
    test_data_dir: "/path/to/test/dataset/folder"
    classes:
      - class1
      - class2
    input_shape: [224, 224]
    val_split: 0.1
    batch_size: 32
    use_weighted_sampler: False
    pin_memory: True

task:
  name: ClassificationTask
  params:
    debug: False
    network:
      name: EfficientNetLite0
      params:
        pretrained: True
    loss:
      name: CrossEntropyLoss
      params:
        is_weighted: False
    metrics:
      - name: Precision
      - name: Recall
    optimizer:
      name: Adam
      params:
        lr: 0.001

callbacks:
  - name: ModelCheckpoint
    params:
      monitor: val_precision
      mode: 'max'
      verbose: True

trainer_params:
  max_epochs: 10
  gpus: 1

export_params:
  output_name: example_classification
  batch_size: 32