run_params:
  name: example_segmentation
  seed: 1

datamodule:
  name: SemanticSegmentationDataModule
  params:
    images_dir: "/path/to/folder/with/images"
    masks_dir: "/path/to/folder/with/masks"
    value_to_class_map:
      0: Background
      1: Class1
      2: Class2
      3: Class3
    batch_size: 8
    train_split: 0.8
    val_split: 0.1
    test_split: 0.1
    shuffle_train: True
    pin_memory: True

train_transforms:
  - name: ToFloat
    params:
      max_value: 255
  - name: LongestMaxSize
    params:
      max_size: 256
  - name: PadIfNeeded
    params:
      min_height: 256
      min_width: 256
      position: top_left
      border_mode: 0
      value: 0
  - name: ToTensor

val_transforms:
  - name: ToFloat
    params:
      max_value: 255
  - name: LongestMaxSize
    params:
      max_size: 256
  - name: PadIfNeeded
    params:
      min_height: 256
      min_width: 256
      position: top_left
      border_mode: 0
      value: 0
  - name: ToTensor


task:
  name: SemanticSegmentationTask
  params:
    visualize_first_batch: True
    model:
      name: UNet
      params:
        input_channels: 3
        num_layers: 5
        features_start: 64
    loss:
      name: CrossEntropyLoss
    metrics:
      - name: IoU
    optimizer:
      name: Adam
      params:
        lr: 0.001

callbacks:
  - name: ModelCheckpoint
    params:
      monitor: val_loss
      mode: 'min'
      verbose: True

trainer_params:
  max_epochs: 1
  gpus: 1

export_params:
  output_name: example_segmentation
  to_onnx: True
