run_params:
  name: example_classification
  seed: 1

datamodule:
  name: ClassificationDataModule
  params:
    data_dir: "/home/judicator/d/data/concrete_test"
    classes:
      - Negative
      - Positive
    input_shape: [227, 227]
    val_split: 0.1
    test_split: 0.1
    batch_size: 8
    use_weighted_sampler: False
    pin_memory: True

task:
  name: ClassificationTask
  params:
    debug: False
    network:
      name: EfficientNetLite0
      params:
        pretrained: True
    loss:
      name: CrossEntropyLoss
      params:
        is_weighted: False
    metrics:
      - name: Precision
    optimizer:
      name: Adam
      params:
        lr: 0.001

callbacks:
  - name: ModelCheckpoint
    params:
      monitor: val_precision
      mode: 'max'
      verbose: True

trainer_params:
  max_epochs: 10
  gpus: 1

export_params:
  output_name: example_classification
  batch_size: 32