run_params:
  name: effnet_lite_96
  seed: 1

datamodule:
  name: ClassificationDataModule
  params:
    data_dir: "/home/dragon/Projects/edge_vision/dvc/sbc_core/Datasets/dooh_classification_3"
    test_data_dir: "/home/dragon/Projects/edge_vision/dvc/sbc_core/Datasets/dooh_classification_3"
    classes:
      - c1
      - c3
      - c6
    input_shape: [96, 96]
    val_split: 0.2
    batch_size: 32
    use_weighted_sampler: True
    pin_memory: True
    num_workers: 4

task:
  name: ClassificationTask
  params:
    debug: False

    network:
      name: EfficientNetLite0
      params:
        pretrained: False
        from_checkpoint: "/home/dragon/Projects/edge_vision/training-pipeline/runs/2021-08-16_14:50:02_effnet_lite_96/checkpoints/epoch=22-step=23344.ckpt"

    loss:
      name: CrossEntropyLoss
      weighted: False
      params:
        {}

    optimizer:
      name: Adam
      params:
        lr: 0.001

    scheduler:
      name: ReduceLROnPlateau
      params:
        patience: 3
        verbose: True

callbacks:
  EarlyStopping:
    monitor: val_loss
    mode: min
    patience: 5
    min_delta: 0.01
    verbose: True
  ModelCheckpoint:
    verbose: True

trainer_params:
  max_epochs: 100
  gpus: 1

export_params:
  output_name: "effnet_lite0_6"
  batch_size: 32