run_params:
  name: test
  seed: 1

datamodule:
  name: ClassificationDataModule
  params:
    data_dir: "/home/judicator/EV/data/vehicle_classification_6_new_v2_train"
    test_data_dir: "/home/judicator/EV/data/vehicle_classification_6_new_test"
    classes:
      - c1
      - c2
      - c3
      - c4
      - c5
      - c6
    input_shape: [32, 32]
    val_split: 0.2
    batch_size: 32
    use_weighted_sampler: True
    pin_memory: True
    num_workers: 4

task:
  name: ClassificationTask
  params:
    debug: True

    network:
      name: BITVehicleClassifierNet
      params:
        input_shape: [32, 32]

    loss:
      name: CrossEntropyLoss
      weighted: True
      params:
        {}

    optimizer:
      name: Adam
      params:
        lr: 0.001

    scheduler:
      name: ReduceLROnPlateau
      params:
        patience: 3
        verbose: True

callbacks:
  EarlyStopping:
    monitor: val_loss
    mode: min
    patience: 5
    min_delta: 0.01
    verbose: True
  ModelCheckpoint:
    {}

trainer_params:
  max_epochs: 100
  gpus: 1

export_params:
  output_name: "bvc_6"
  batch_size: 32